# syntax=docker/dockerfile:1

# ---- Build stage ----
FROM golang:1.26 AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /mockservice ./cmd/mockservice

# ---- Runtime stage ----
FROM gcr.io/distroless/static-debian12
WORKDIR /app

COPY --from=build /mockservice /app/mockservice

EXPOSE 8081
ENTRYPOINT ["/app/mockservice"]